---
title: "Proposal: EMS in British Columbia area (2009-2014)"
subtitle: "DATA 450 Capstone"
author: "Robert Zhong"
date: 02/08/2024
date-format: long
bibliography: references.bib
number-sections: true
format:
  pdf: default
jupyter: python3
---

# Introduction

EMS is an essential part of the healthcare system. It plays a role in delivering direct medical care and transportation to patients requiring attention. This analysis explores the different factors that affect EMS response times and examine how they impact patient outcomes in relation to the event type and location to the efficiency of the overall system. There will also be a deeper analysis on the MPDS codes(Medical Priority Dispatch System), a way of categorizing and prioritizing EMS incidents.
Objectives:

* Assess the impact of EMS response times on patient outcomes.
* Examine the temporal changes in EMS response times over a specified period.
* Identify factors contributing to changes in response times.
* Compare response times and outcomes between different locations.
* Evaluate the effect of using lights and sirens on response times and safety.
* Analyze the influence of MPDS prioritization on response efficiency.

# Dataset

* [There are 2,411,093 rows, and each row represents a 9/11 call]
* Call year: The year the call was received
* Community type: The community type (Remote, Rural, Metro, Urban, No-Station)
* Call location: The location (municipality) —partial — with at least 10,000 total calls per year
* MPDS Code: The intital/Final MPDS code used for the call
* Description: Description on the event
* Qualification: Required qualification for service provider
* MPDS Determinant code: Initial/Final "MPDS Determinant" code assigned to the call[A-E. Letter "A" indicates the lowest priority incident and "E" indicates the highest priority incident]
* Response mode: The code used to respond to a call
* Event Cancelled: Whether the event was cancelled
* Response time: The time in minutes from when the call was received to when the first ambulance was on scene
* To Hospital time: The time in minutes from when the call was received to when the first ambulance arrived at hospital 

[This data was obtained from the Provincial Health Services Authority through a Freedom of Information request. Chad Skelton, a journalist for the Vancover Suns made it available.]

# Data Acquisition and Processing

* First off, I will have to make sure the datatypes a correct.
* Then I might fill missing vlaues, but I will most likely get rid of it when Im doing modeling.
* Save raw data for recovery and experimentation

# Research Questions and Methodology

Questions:

1. **What factors influence ambulance response times?**
   - **Sub Research**:
     - How do response times vary by event type, community type and response code?
     - What is the impact of MPDS codes on response times?
     - How does the change from initial to final MPDS codes affect response times?
     - Are there significant differences in response times over the years, and what might be contributing to these changes?

   **Plan**: Use Kruskal-Wallis test, ANOVA, regression analysis, correlation analysis, and time series analysis to explore these factors. Tables, box plots, bar charts, and line graphs might be used. Compare the initial and final MPDS codes to see how often they change and in what direction (from less to more severe). Random forests or gradient boosting to handle nonlinear relationships and interactions between variables more effectively. Clustering to identify patterns or groups within the data based on response times and other relevant factors.

2. **How do emergency response strategies and outcomes relate to MPDS codes and call cancellation?**
   - **Sub Reaserch**:
     - Does the final MPDS determinant code affect the likelihood of an event being cancelled?
     - Is there a relationship between the initial and final MPDS codes and the outcome of the emergency event?
     - What are the most frequent call types, and how do they correlate with response times and chances of the call getting cancelled?

   **Plan**: Logistic regression to assess cancellation likelihood, chi-square tests for categorical relationships, and frequency analysis. Results will include summaries, correlation coefficients, and charts of cancellation rates. Network analysis to visualize how different types of calls are interconnected and how they influence each other.

3. **What is the relationship between response times and hospital arrival times?**
   - **Plan**: Calculate Pearson correlation coefficients and present findings with scatter plots and trend lines. Cluster based on trends in scene response and hospital arrival times to identify periods or groups with similar characteristics.

4. **How does the variety and frequency of emergency calls differ by community type?**
   - **Plan**: Calculate diversity metrics such as the Shannon diversity index for different areas and present findings in comparative tables and distribution charts.

5. **What insights can be drawn from the evolution of emergency response strategies over time, as indicated by changes in MPDS codes?**
   - **Plan**: Analyze trends in MPDS code changes with qualitative summaries. Change point detection to identify significant shifts in emergency response strategies over time.

6. **How does the differnet response codes affect the response time?**
    - **Plan**:  t-tests or non-parametric tests to assess the significance of the differences.

7. **What do all these results say about the qualifications and the need of first responders?**
    - **Plan**: Merge the MPDS code to get a bigger picture.

* [NOTE: This is just a basic outline. Might use one hot encoding]

# Work plan

**Week 4 (2/12 - 2/18):** 

* Set up project management tools
* Begin data cleaning, standardizing formats
* Dividing into subsets

**Week 5 (2/19 - 2/25):**

 * Examine the change from initial to final MPDS codes and trends over the years.
 * Time series analysis [2 hours]
 * Change point detection [2 hours]
 * Random forests/Gradient boosting [4 hours]

**Week 6 (2/26 - 3/3):**

 * Analyze response times vary by event type, community type, and response code; impact of MPDS codes.
 * Kruskal-Wallis test [2 hours]
 * ANOVA [2 hours]
 * Other regression [2 hours]

**Week 7 (3/4 - 3/10):**

* Relationship between MPDS codes and call cancellation
* Logistic regression [2 hours]
* Chi-square tests [2 hours]
* Network analysis [2 hours]
* Presentation prep and practice (4 hours)

**Week 8 (3/11 - 3/17):** 

* Getting relationship between scene response times and hospital arrival times.
* Pearson correlation [2 hours]
* Clustering [2 hours]
* Poster prep (4 hours)
* Presentation peer review (1.5 hours)

**Week 9 (3/25 - 3/31):** *Final Poster due Sunday 3/31*.

* Peer feedback (3.5 hours)
* Poster revisions (3.5 hours)

**Week 10 (4/1 - 4/7):** 

* How emergency calls vary by community type.
* Shannon index [2 hour]
* Tables [2 hour]

**Week 11 (4/8 - 4/14):**

* Get changes in emergency response strategies indicated by MPDS code evolution.
* Timelines [2 hour]
* qualitative analysis [2 hour]

**Week 12 (4/15 - 4/21):**

*  t-tests, non-parametric tests [2 hours]
* Compile and interpret findings [5 hours]

**Week 13 (4/22 - 4/28):**

* Draft blog post (4 hours).

**Week 14 (4/29 - 5/5):**

* Peer feedback (3 hours)
* Blog post revisions (4 hours)

**Week 15 (5/6 - 5/12):**  

* Blog post revisions (2 hours)
* Peer feedback (2 hours)

* [Timeline subject to change]

# References

[Provincial Health Services Authority. (2015). B.C. Ambulance Raw Data. Chad Skelton] 
https://drive.google.com/drive/folders/0B5AELJGlYc4JfnQxbHNLM3VwemlCUVlsN2JUZVhxUi1iX0lkWTdVb3VuRkdJODNtN2Nsc28?resourcekey=0-LFZispDzmUuh4hwfAKbYJQ
